### ISSUE TITLE
Preserve levels of Test

### ISSUE THREAD

**Issue by kliegl** [RePsychLing/SMLP2021#2] opened 2021-04-10 11:47 UTC
Arrows does not preserve the order of levels of Test.
As you don't like CategoricalArrays or DataFramesMeta, how can I resort levels of Test with DataAPI (or whatever)?

**Comment by dmbates** [comment] 2021-04-10 17:09
The issue of the order of the levels may be resolved in the next update to the Arrow.jl package.  See https://github.com/JuliaData/Arrow.jl/pull/164   The problem is that the StatsModels.jl uses `DataAPI.levels(f)` to get the levels of factor `f` and without a method defined for the `Arrow.DictEncoded` types it would fall back on the default, which sorts the levels.

If the ordering of the levels is important we should save them as an ordered factor.  When a new version of Arrow.jl is released the levels will be in the original order in the Arrow.Table result but converting the factor to other forms like CategoricalArray or PooledArray may re-arrange them unless they are stored as ordered factors.

We may need more general representations of ordered factors to get around this.  Let's keep the issue open.

**Comment by kliegl** [comment] 2021-04-10 17:12
Actually, as far as MixedModels.jl is concerned, I realized afterwards that I can re-order levels with the levels kwarg when constructing the contrasts. This is even didactically useful because one could argue for best practice to have the levels stored with the contrast construction. So until we get to plotting and other stuff, no rush from my side.

**Comment by kliegl** [comment] 2021-04-10 17:17
It does not seem to be required but would it be good, after reading the arrows table, to convert strings to factors in the dataframe?

**Comment by kliegl** [comment] 2021-04-11 09:41
It looks like we can close this issue?

**Closed** 2021-04-11 15:43 UTC
